### ISSUE TITLE
Library Incompatabilities

### ISSUE THREAD

**Issue by Jeff-Winchell** [04mayukh/YoungSheldon-at-SemEval-2021-Task-7-HaHackathon#1]
I cannot install the required libraries due to incompatabilities in the currently available libraries.

This command fails
conda create --yes --name Haha_Mayukh nltk pandas tensorflow-gpu notebook tf-models-official --channel conda-forge --channel hcc

with a long list of libraries (mostly ones required by the above libraries) that are incompatible with each other.

pip doesn't check for incompatabilities as thoroughly as conda does, and I noticed that some libraries used in subtask 1b.ipynb weren't installed via pip commands in the notebook. So I'm not sure how to replicate this code.

Do you have any suggestions?

**Comment by Jeff-Winchell** [comment]
The problem seems to be in importing the tf-models-official library. Everything else installs fine.

**Comment by 04mayukh** [comment]
tf-models-official in the latest versions comes by default with tf. Also for the code in the given notebooks tf-models-official is not used. It provides support for adamw optimiser but we used adam in our final approach. In order to run the code you can proceed without tf-models-official and see if it works out.

If you face any other issues please let me know.

**Comment by Jeff-Winchell** [comment]
Yes, this code didn't use that library. And I was able to run the code to completion (after I found solutions to the other 3 issues).

**Comment by 04mayukh** [comment]
Good to know you were able to solve the issue. May you need any more assistance you can create a new issue.
